orders/urls.py
from django.urls import include, path
from django.conf.urls import url
from .views import OrderCreateView
from . import views

urlpatterns = [
    path('', views.home, name='orders-home'),
    path('orders/create/', OrderCreateView.as_view(), name='orders-create'),
    path('orders/history/', views.order_history, name='orders-history'),
    path('ajax/load-meal_type/', views.load_meal_type, name='ajax_load_meal_type'),
    path('ajax/load-size/', views.load_size, name='ajax_load_size'),
    path('ajax/load-meal_addition/', views.load_meal_addition, name='ajax_load_meal_addition'),
    path('ajax/load-price/', views.load_price, name='ajax_load_price')
]

pizza/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    # login is a standard form provided by django (it is customised using crispy forms)
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # logout is also handled by django
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('orders.urls')),
    path('', include('shopping_cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (add_to_cart, delete_from_cart, order_details, checkout, success, update_transaction_records)

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name="purchase_success"),
    #url(r'^success/$', success, name='purchase_success'),
    path('item/delete/<int:item_id>/', delete_from_cart, name="delete_item"),
    #url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name="checkout"),
    path('update-transaction/<str:token>/', update_transaction_records, name='update_records'),
]

orders/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Meal(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class Meal_Addition(models.Model):
    name = models.CharField(max_length=64)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    price = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f"{self.name} ({self.meal})"


class Size(models.Model):
    size = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.size}"


class Meal_Type(models.Model):
    name = models.CharField(max_length=64)
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE, null=True)
    size = models.ManyToManyField(Size)
    meal_addition = models.ManyToManyField(Meal_Addition, blank=True)
    
    def __str__(self):
        return f"{self.name}"


class Price(models.Model):
    price = models.FloatField(default=0)
    meal_type = models.ManyToManyField(Meal_Type)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    
    def __str__(self):
        # extract values from list of meal types and convert them to a string
        l = list(self.meal_type.values_list('name', flat=True))
        s = [str(i) for i in l] 
        meal_types_list = ", ".join(s)
        return f"{self.size} ({meal_types_list}) (${self.price})"


class Item(models.Model):
    meal = models.ForeignKey(Meal, on_delete=models.CASCADE)
    meal_type = models.ForeignKey(Meal_Type, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    meal_addition = models.ManyToManyField(Meal_Addition, blank=True)
    price = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return f"{self.size} {self.meal_type} (${self.price})"

orders/forms.py
from django import forms
from .models import Item, Meal, Meal_Type, Size, Meal_Addition, Price

class OrderForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('meal', 'meal_type', 'size', 'meal_addition')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # establecer menús desplegables como vacíos hasta que se seleccione una comida del primer menú desplegable 
        self.fields['meal_type'].queryset = Meal_Type.objects.none()
        self.fields['size'].queryset = Size.objects.none()
        self.fields['meal_addition'].queryset = Meal_Addition.objects.none()

        # si se ha seleccionado una comida del menú desplegable
        if 'meal' in self.data:
            try:
                meal_id = int(self.data.get('meal'))
                self.fields['meal_type'].queryset = Meal_Type.objects.filter(meal_id=meal_id).order_by('meal')
            except (ValueError, TypeError):
                pass 
        
        # si se ha seleccionado un typo de comida del menú desplegable 
        if 'meal_type' in self.data:
            try:
                meal_type = int(self.data.get('meal_type'))
                self.fields['size'].queryset = Size.objects.filter(meal_type=meal_type).order_by('size')
                self.fields['meal_addition'].queryset = Meal_Addition.objects.filter(meal_type=meal_type).order_by('name')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            self.fields['size'].queryset = self.instance.meal_type.size_set.order_by('size')
            self.fields['meal_addition'].queryset = self.instance.meal_type.meal_addition_set.order_by('name')

    # validar los ingredientes y obtener el total del precio de la orden
    def clean_meal_addition(self):
        meal_addition = self.cleaned_data['meal_addition']
        meal_type = self.cleaned_data['meal_type']
        size = self.cleaned_data['size']
        meal = str(self.cleaned_data['meal'])

        # si es seleccionada pizza debe escoger los ingredientes
        if 'Pizza' in meal:
            if '1 ingrediente' in str(meal_type):
                if len(meal_addition) != 1:
                    raise forms.ValidationError('Debes seleccionar 1 ingrediente')
            if '2 ingredientes' in str(meal_type):
                if len(meal_addition) != 2:
                    raise forms.ValidationError('Debes seleccionar 2 ingrediente')
            if '3 ingredientes' in str(meal_type):
                if len(meal_addition) != 3:
                    raise forms.ValidationError('Debes seleccionar 3 ingrediente')

        # obtenga el precio para el tipo de comida seleccionado
        meal_price = Price.objects.filter(meal_type=meal_type, size=size)
        total_price = float()
        for item in meal_price:
            total_price = float(item.price)
        
        # si el tipo de comida es un sub, agregue el costo de cualquier adición al precio total
        if 'Sub' in meal:
            for item in meal_addition:
                total_price = total_price + float(item.price)
                
        return meal_addition

orders/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import CreateView, DetailView
from django.urls import reverse_lazy, reverse
from .models import Meal, Item, Meal_Type, Size, Meal_Addition, Price
from .forms import OrderForm
from users.models import Cart
from shopping_cart.models import Order
from django.template.defaulttags import register
from django.contrib.auth.mixins import LoginRequiredMixin
import json


# used to extract values from menu dictionary on the html page
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


# Create your views here.

def home(request):
    # get menu data and pass into context
    menu = {}
    price = []
    toppings = []
    sub_additions = {}
    for item in Meal_Type.objects.all():
        l = list(item.meal_addition.values_list('name', flat=True))
        meal_additions_list = [str(i) for i in l]
        sub_additions[item.name] = meal_additions_list
    for item in Meal.objects.all():
        l = list(Meal_Type.objects.filter(meal=item).order_by('name'))
        meal_types_list = [str(i) for i in l]
        menu[item.name] = meal_types_list
    for item in Price.objects.all():
        l = list(item.meal_type.values_list('name', flat=True))
        meal_types_by_price_list = [str(i) for i in l]
        temp = {}
        temp['size'] = item.size
        temp['price'] = item.price
        temp['meal_types'] = meal_types_by_price_list
        price.append(temp)
    meal_additions = Meal_Addition.objects.all()
    for item in list(meal_additions):
        if "Pizza" in str(item):
            toppings.append(item)
    context = {
        'title': 'Inicio',
        'menu': menu,
        'prices': price,
        'toppings': toppings,
        'sub_additions': sub_additions
    }
    return render(request, 'orders/home.html', context)


# automatically generates the order_form.html page when navigated to
temp = {}
class OrderCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = OrderForm
    success_url = '/add-to-cart/'
    context_object_name = 'Create'

    def form_valid(self, form):
        # assign the current user as the owner of the order
        form.instance.user = self.request.user
        # assign the price of the order
        form.instance.price = temp['price']
        return super().form_valid(form)


# order form dropdown menu - meal types
def load_meal_type(request):
    meal_id = request.GET.get('meal')
    meal_type = Meal_Type.objects.filter(meal_id=meal_id).order_by('name')
    context = {
        "meal_type": meal_type
    }
    return render(request, 'orders/dropdown_list_options.html', context)


# order form dropdown menu - sizes
def load_size(request):
    temp['meal_type'] = request.GET.get('meal_type')
    size = Size.objects.filter(meal_type=temp['meal_type']).order_by('size')
    context = {
        "size": size
    }
    return render(request, 'orders/dropdown_list_options.html', context)


# order form dropdown menu - meal additions
def load_meal_addition(request):
    # this will only get passed when a different meal type is selected and the additions menu needs to be reset
    if (request.GET.get('meal_type')):
        meal_addition = Meal_Addition.objects.filter(meal_type=(request.GET.get('meal_type'))).order_by('name')
    # this uses the meal type which is saved to temp in the load_size function above
    else:
        meal_addition = Meal_Addition.objects.filter(meal_type=temp['meal_type']).order_by('name')
    context = {
        "meal_addition": meal_addition
    }
    return render(request, 'orders/dropdown_list_options.html', context)


# get the total cost of the meal
# temp1 and temp2 are used in order to calculate the price of any meal additions
temp1 = {}
def load_price(request):
    # if a size is selected then save it and get the price for the meal
    if (request.GET.get('size')):
        temp['size'] = request.GET.get('size')
        meal_price = Price.objects.filter(meal_type=temp['meal_type'], size=temp['size'])
        for item in meal_price:
            temp1['price'] = float(item.price)
            temp['price'] = temp1['price']
        context = {
            "total_price": temp['price']
        }
        return render(request, 'orders/price.html', context)

    # if any meal additions are selected then their price (if any) is added to the total
    if (request.GET.get('meal_addition')):
        meal_additions_list = json.loads(request.GET.get('meal_addition'))
        for each_addition in meal_additions_list:
            temp2 = {'price': 0.0}
            for item in each_addition:
                price = Meal_Addition.objects.get(pk=item)
                if (price.price):
                    temp2['price'] = (temp2['price'] + price.price)
            temp['price'] = (temp1['price'] + temp2['price'])
        context = {
            "total_price": temp['price']
        }
        return render(request, 'orders/price.html', context)


def order_history(request):
    my_user_cart = Cart.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_cart)
    context = {
        'my_orders': my_orders
    }
    return render(request, "orders/history.html", context)

orders/templates/orders/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'orders/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'orders/bootstrap.min.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Imperial+Script&display=swap" rel="stylesheet">
    {% if title %}
    <title>Delicious Pizza - {{ title }}</title>
    {% else %}
    <title>Delicious Pizza</title>
    {% endif %}
</head>
<style>
    body {
        background-image: url(https://res.cloudinary.com/dzlbg8ni6/image/upload/v1639891481/istockphoto-1083487954-612x612_tmafib.jpg);
        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover;
        background-attachment: fixed;
    }
</style>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'orders-home' %}"><h1 style="font-size: 30px; font-family:'Imperial Script', cursive;">Delicious Pizza</h1></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'orders-home' %}">Inicio</a>
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'orders-create' %}">Crear Orden</a>
                        <a class="nav-item nav-link" href="{% url 'shopping_cart:order_summary' %}">Carrito</a>
                        <a class="nav-item nav-link" href="{% url 'orders-history' %}">Historial Ordenes</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'profile' %}">Perfil</a>
                        <a class="nav-item nav-link" href="{% url 'logout' %}">Cerrar Sesion</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'login' %}">Iniciar Sesion</a>
                        <a class="nav-item nav-link" href="{% url 'register' %}">Registrarme</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                {% block sidebar %}{% endblock %}
            </div>
        </div>
    </main>
        <!--  JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/a5428e3a4b.js"></script>
        <script src="{% static 'orders/base.js' %}"></script>
        {% block script %}{% endblock script %}
</body>

</html>

orders/templates/orders/dropdown_list_options.html
<option>----------------</option>
{% if meal_type %}
    {% for type in meal_type %}
    <option value="{{ type.pk }}">{{ type.name }}</option>
    {% endfor %}
{% endif %}
{% if size %}
    {% for item in size %}
    <option value="{{ item.pk }}">{{ item.size }}</option>
    {% endfor %}
{% endif %}
{% if meal_addition %}
    {% for item in meal_addition %}
    <option value="{{ item.pk }}">{{ item.name }}</option>
    {% endfor %}
{% endif %}

orders/templates/orders/history.html
{% extends 'orders/base.html' %}
{% block content %}
    <div>
        <table class="table table-dark" style="margin-top: 10px;">
            <tr>
                <th>Fecha de orden:</th>
                <th>Codigo</th>
                <th>Items</th>
                <th>Precio</th>
            </tr>
            {% for order in my_orders %}
                <tr>
                    <td>{{ order.date_ordered }}</td>
                    <td>{{ order.ref_code }}</td>
                    <td>
                        <ul>
                            {% for item in order.items.all %}
                                <li>
                                    {{ item.item }}
                                </li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>${{ order.get_cart_total }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4"> Todavia no hay ordenes.</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="4">
                    <a href="{% url 'orders-create' %}" style="color:black;" class="btn btn-warning pull-left">
                        {% if not order %}Continuar comprando{% else %}Añadir Item al carrito {% endif %}
                    </a>
                </td>
            </tr>
        </table>
    </div>
{% endblock %}

orders/templates/orders/home.html
{% extends 'orders/base.html' %}
{% block content %}
    {% if menu %}
        <div class="menu" style="margin-top: 20px;">
            <table class="table table-dark">
                <thead>
                    <tr style="height: 70px;">
                        <th id="menu-title" scope="row" colspan="3" style="width: 100%; height: 100%; text-align: center;"><h2 style="height: 100%; font-size: 50px; font-family:'Imperial Script', cursive;">Menú</h2></th>
                    </tr>
                </thead>
                <tbody>
                    {% for meal in menu %}
                        <tr>
                            <th colspan="3" class="table-secondary" style="color: black;">{{ meal }}</th>
                        </tr>
                        {% for mealType1 in menu|get_item:meal %}
                            <tr>
                                <td scope="row">{{ mealType1 }}</td>
                                {% if prices %}
                                    {% for item in prices %}
                                        {% for mealType2 in item.meal_types %}
                                            {% if mealType2 == mealType1 %}
                                                <td>{{ item.size }} C${{ item.price }}</td>
                                            {% endif %}
                                        {% endfor %}
                                    {% endfor %}
                                {% endif %}
                            </tr>
                            {% if "*" in mealType1 %}
                                {% if sub_additions %}
                                    {% for item in sub_additions %}
                                        {% if "*" in item %}
                                            {% for item2 in sub_additions|get_item:item %}
                                                {% if "Cheese" in item2 %}
                                                {% else %}
                                                <tr>
                                                    <td scope="row">&nbsp;&nbsp;&nbsp; - Add {{ item2 }}</td>
                                                </tr>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        {% if meal == "Sub" %}
                            <tr>
                                <td scope="row">&nbsp;&nbsp;&nbsp; - Add Cheese to any sub (50c)</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}
{% block sidebar %}
    {% if toppings %}
        <div class="menu" style="margin-top: 20px;">
            <table class="table table-dark">
                <thead>
                    <tr>
                        <th id="toppings-title" scope="row" colspan="3"><h2 style="height: 100%; font-size: 30px; font-family:'Imperial Script', cursive;">Ingredientes</h2></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in toppings %}
                        <tr scope="row">
                            <td>{{ item.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

orders/templates/orders/item_form.html
{% extends 'orders/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    section{
        color: blanchedalmond;
    }
</style>
    <section class="card border-primary" style=" margin-top: 10px; padding: 10px;">
        <form method="POST" id="orderForm" data-meal_type-url="{% url 'ajax_load_meal_type' %}" data-size-url="{% url 'ajax_load_size' %}" 
         data-meal_addition-url="{% url 'ajax_load_meal_addition' %}" novalidate>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Crear Orden</legend>
                <span id="meal">{{ form.meal|as_crispy_field }}</span>
                <span id="meal-type">{{ form.meal_type|as_crispy_field }}</span>
                <span id="size">{{ form.size|as_crispy_field }}</span>
                <span id="meal-additions">{{ form.meal_addition|as_crispy_field }}</span>
            </fieldset>
            <div class="form-group">
                <button id="add-to-cart" class="btn btn-outline-success" type="submit" style="margin-top: 5px;" disabled>Añadir al carrito</button>
            </div>
        </form>
        <div id="price" data-price-url="{% url 'ajax_load_price' %}" >
            <p>Total: C$<span id="price-value"></span></p>
        </div>
    </section>
{% endblock %}

orders/templates/orders/price.html
{% if total_price %}
    <p value="{{ total_price }}">{{ total_price }}</p>
{% endif %}