pizza/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    # login is a standard form provided by django (it is customised using crispy forms)
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    # logout is also handled by django
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('orders.urls')),
    path('', include('shopping_cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (add_to_cart, delete_from_cart, order_details, checkout, success, update_transaction_records)

app_name = 'shopping_cart'

urlpatterns = [
    path('add-to-cart/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name="purchase_success"),
    #url(r'^success/$', success, name='purchase_success'),
    path('item/delete/<int:item_id>/', delete_from_cart, name="delete_item"),
    #url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name="checkout"),
    path('update-transaction/<str:token>/', update_transaction_records, name='update_records'),
]

shopping_cart/models.py
from __future__ import unicode_literals
from django.db import models
from users.models import Cart
from orders.models import Item

# Create your models here.

class OrderItem(models.Model):
    item = models.OneToOneField(Item, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return str(self.item)


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.item.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

shopping_cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from users.models import Cart
from orders.models import Item
from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order, Transaction
import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.

def get_user_pending_order(request):
    # get order for the correct user
    user_cart = get_object_or_404(Cart, user=request.user)
    order = Order.objects.filter(owner=user_cart, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request):
    # get the user cart
    user_cart = get_object_or_404(Cart, user=request.user)
    # filter items by latest
    item = Item.objects.filter(user=request.user).order_by('timestamp').last()

    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(item=item)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_cart, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.success(request, "Item added to cart!")
    context = {
        'title': 'Cart'
    }
    return redirect('shopping_cart:order_summary')


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted!")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
        'title': 'Cart'
    }
    return render(request, 'shopping_cart/order_summary.html', context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        try:
            token = request.POST['stripeToken']
            charge = stripe.Charge.create(amount=int(100*existing_order.get_cart_total()), currency='usd', description='Example charge', source=token)
            return redirect(reverse('shopping_cart:update_records', kwargs={'token': token}))
        except stripe.CardError as e:
            messages.warning(request, "Your card has been declined.")

    context = {
        'order': existing_order,
        'STRIPE_PUBLISHABLE_KEY': publishKey,
        'title': 'Checkout'
    }
    return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()
    
    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # add products to user cart
    user_cart = get_object_or_404(Cart, user=request.user)
    # get the products from the items
    order_products = [item.item for item in order_items]
    user_cart.item.add(*order_products)
    user_cart.save()

    # create a transaction
    transaction = Transaction(cart=request.user.cart, token=token, order_id=order_to_purchase.id, amount=order_to_purchase.get_cart_total(), success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()

    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.success(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('orders-history'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/purchase_success.html', {})

shopping_cart/templates/shopping_cart/checkout.html
{% extends 'orders/base.html' %}
{% load static %}
{% block content %}
    <section style="margin-top: 20px;">
        <table class="table table-dark">
            <tr>
                <td colspan="2"><h4>Pago de Orden</h4></td>
            </tr>
            <tr>
                <td>
                    {% for item in order.get_cart_items %}
                        <tr>
                            <td>{{ item.item.size }} {{ item.item.meal_type }}</td>
                            <td>C${{ item.item.price }}</td>
                        </tr>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                {% if order.get_cart_total != None %}
                    <td>
                        <strong class="pull-right">Total:</strong>
                    </td>
                    <td>
                        C$<strong>{{ order.get_cart_total }}</strong>
                    </td>
                {% endif %}
            </tr>
        </table>
    </section>
    <h2>Metodo de pago:</h2>
    <div class="card" style="padding: 10px;">
        <script src="https://www.paypal.com/sdk/js?client-id=AdNaKOnAyPmqD6cU32JdsSqIWmtGM9b8AzBxfrBCGSEuLDDC_kqwW4Vj95MoBlPDkpMvvFKP24UBHELF&currency=USD"></script>
        <div id="paypal-button-container"></div>
        <script>
        paypal.Buttons({
    
            createOrder: function (data, actions) {
    
                // This function sets up the details of the transaction, including the amount and line item details.
    
                return actions.order.create({
    
                    purchase_units: [{
    
                        amount: {
    
                            value: '{{ order.get_cart_total }}'
    
                        }
    
                    }]
    
                });
    
            },
    
            onApprove: function (data, actions) {
    
                // This function captures the funds from the transaction.
    
                return actions.order.capture().then(function (details) {
    
                    // This function shows a transaction success message to your buyer.
                    window.location.href = "/succesBuy";
                    alert('Transaction completed by ' + details.payer.name.given_name);
    
                });
    
            }
    
        }).render('#paypal-button-container');
        </script>
        
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

{% endblock content %}

shopping_cart/templates/shopping_cart/order_summary.html
{% extends 'orders/base.html' %}
{% block content %}
    <table class="table table-hover table-dark" style="margin-top: 10px;">
        <tr class="text-center">
            <th>No.</th>
            <th>Item</th>
            <th>Precio</th>
        </tr>
        {% for item in order.get_cart_items %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    {{ item.item.size }} {{ item.item.meal_type }}
                    <span class="float-right">
                        <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" 
                            class="text-danger" onclick="return confirm_delete();">
                            <i class="fas fa-trash"></i>
                        </a>
                    </span>
                </td>
                <td>C${{ item.item.price }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3"> Aún no ha agregado ningún elemento. </td>
            </tr>
        {% endfor %}
        <tr>
            {% if order.get_cart_total != None %}
                <td colspan="2">
                    <strong class="pull-right">Orden Total:</strong>
                </td>
                <td colspan="1">
                    C$<strong>{{ order.get_cart_total }}</strong>
                </td>
            {% endif %}
        </tr>
        <tr>
            <td colspan="1">
                <a href="{% url 'orders-create' %}" class="btn btn-warning pull-left">
                    {% if order %}Continuar comprando{% else %}Añadir item al carrito {% endif %}
                </a>
            </td>
            <td colspan="2">
                {% if order.get_cart_items %}
                    <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceder al pago</a>
                {% endif %}
            </td>
        </tr>
    </table>
    <script>
        function confirm_delete() {
            return confirm("¿Quieres eliminar este artículo del carrito?");
        }
    </script>
{% endblock content %}